config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  root 'welcome#index'
  
  resources :comments

  resources :categories, only: [:index, :show]

  resources :users, only: [:show, :index] do
    resources :projects, except: [:new]
  end

  resources :projects do
    resources :comments
    get 'like'
  end

  get 'current_user' => "users#current_user"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    if(params[:project_id])
      @project = Project.find(params[:project_id])
    end
    @comments = @project.comments
  end

  def new
    @comment = Comment.new(project_id: params[:project_id])
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      @project = Project.find(@comment.project_id)
      current_user.comments << @comment
      @project.comments.build(comment_params)
      render json: @comment, status: 201
      #redirect_to project_path(@project)
    else
      render "comments/new"
    end
  end

  def show
    @comment = Comment.find(params[:id])
    @project = Project.find(@comment.project_id)
    @user_name = User.find(@comment.user_id).name
=begin
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @comment }
    end
=end
  end

  def edit
    @comment = current_user.comments.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    if @comment.save
      flash[:success] = "Comment updated."
      redirect_to @comment
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @project = Project.find(@comment.project_id)
    flash[:success] = "Comment deleted."
    redirect_to project_path(@project)
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :project_id, :user_id, user_attributes:[:username])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
  <%= f.hidden_field :project_id %>
  <%= f.label "Comment" %><br>
  <%= f.text_area :content, class: 'text-area' %><br><br>
  <%= f.submit class: 'btn btn-primary' %>
<%end%>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form" %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<% @comments.each do |comment| %>
  <%= comment.content %><br>
<%end%>

app/views/comments/new.html.erb
<h1><%= Project.find(@comment.project_id).title %></h1>
<br>

<% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |msg| %>
      <p><%= msg %>.</p>
    <% end %>
<% end %>

<%= render "form" %>

app/views/comments/show.html.erb
<%= flash[:success] if flash[:success] %><br><br>

<% if current_user && current_user.comments.include?(@comment) %>
  <%= link_to "Edit comment", edit_comment_path(@comment), class: 'form_button' %>
  <%= link_to 'Delete comment',  project_comment_path(@project, @comment),
      data: { confirm: 'Are you sure you want to delete this comment?' }, method: :delete, class: 'form_button' %>
<%end%>

<h1><%= @project.title %></h1>

<%= @comment.content %><br><br>
By: <%= @user_name %><br><br>

<%= link_to "Back to project", project_path(@project) %>