config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  root 'welcome#index'
  
  resources :comments

  resources :categories, only: [:index, :show]

  resources :users, only: [:show, :index] do
    resources :projects, except: [:new]
  end

  resources :projects do
    resources :comments
    get 'like'
  end

  get 'current_user' => "users#current_user"

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :project_categories
  has_many :categories, through: :project_categories
  has_many :comments

  belongs_to :creator, :class_name => "User"

  has_many :commenters, through: :comments, :class_name => "User"

  validates :title, presence: true
  has_attached_file :image
  validates_presence_of :image
  validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      category = Category.find_or_create_by(category_attribute)
      self.categories << category
    end
  end

  def update_likes(project_id)
    @project = Project.find(project_id)
    @project.likes = @project.likes + 1
    @project.save
    @project
  end

  def self.trending_projects
    where("likes > 10")
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if params[:user_id]
      @projects = User.find(params[:user_id]).created_projects
    else
      @projects = Project.all
    end
    @trending_projects = Project.trending_projects
  end
  
  def new
    @project = current_user.created_projects.build() 
    @all_categories = Category.all.reject {|category| category.name.empty?}
  end

  def create
    @project = current_user.created_projects.build(project_params) 
    @all_categories = Category.all.reject {|category| category.name.empty?}
    @project.user_id = current_user.id
    if @project.save
      redirect_to project_path(@project)
    else
      render "projects/new"
    end
  end

  def show
    if params[:user_id]
      @project = User.find(params[:user_id]).created_projects.find(params[:id])
    else
      @project = Project.find(params[:id])
    end
    
    @user_name = User.find(@project.user_id).name
    @comments = @project.comments

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @project}
      format.json { render json: @comments }
      format.json { render json: @comments["user"] }
    end

  end

  def edit
    @project = current_user.created_projects.find(params[:id])
    @all_categories = Category.all.reject {|category| category.name.empty?}
  end

  def like
    @project = Project.find(params[:project_id])
    @project.update_likes(params[:project_id])
    redirect_to @project
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    if @project.save
      flash[:success] = "Project successfully updated."
      redirect_to @project
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "Project successfully deleted."
    redirect_to projects_path
  end

  private

    def project_params
      params.require(:project).permit(:title, :user_id, :image, :short_blurb, :location, category_ids:[], categories_attributes: [:name])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, html: {multipart: true} do |f| %>

  <%= f.label "Title" %><br>
  <%= f.text_field :title, class: 'text-field' %><br><br>
  <%= f.label "Image" %>

  <center><%= f.file_field :image, class: 'form-control'%></center><br>

  <%= f.label "Short Blurb" %><br>
  <%= f.text_area :short_blurb, class: 'text-area' %><br><br>
  <%= f.label "Location" %><br>
  <%= f.text_field :location, class: 'text-field' %><br><br>

  <p>Choose a category:</p>

  <%= f.collection_check_boxes :category_ids, @all_categories, :id, :name do |b| %>
  <%= b.check_box %>
  <%= b.label %><br>
  <%end%>
  <br>
  
  <p>Or create a new category:</p>
  <%= f.fields_for :categories, @project.categories.build do |categories_fields| %>
    <%= categories_fields.text_field :name, class: 'text-field' %> 
  <% end %><br><br>

  <%= f.submit class: 'btn btn-primary' %>

<%end%>

app/views/projects/edit.html.erb
<p class="create_new">Edit your project</p>

<% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
<% end %>

<%= render "form" %>

app/views/projects/home.html.erb
<body class="home">
  <p class="heading">A place for your creative projects.</p><br>
  <%= link_to "Get Started", new_user_registration_path, :class => "start" %>
</body>

app/views/projects/index.html.erb
<%= flash[:success] if flash[:success] %>
<h3>We have a wide a variety of projects.</h3><br>
<%if current_user %>
  <p><%= link_to "Add yours today.", new_project_path, :class => "form_button" %></p>
<%else%>
  <p><%= link_to "Add yours today.", new_user_session_path, :class => "form_button" %></p>
<%end%>
<br><br>

<h2>What's Popular</h2>
<% @trending_projects.each do |project| %>
  <%= project.title %>
<%end%>
<br><br><br>

<%if params[:user_id]%>
  <h2>My Projects</h2><br>
<%else%>
  <h2>Discover Awesome Projects</h2><br>
<%end%>

<div class="all_projects">
<% @projects.each do |project| %>
  <% if params[:user_id] %>
    <center><div class="each">
    <%= link_to project.title, user_project_path(params[:user_id], project.id), :class => "project_title" %><br>
    <p class="created">Created by: <%= User.find(project.user_id).name %></p>
    <%= link_to image_tag(project.image.url, class: 'media-object'), project.image.url, target: '_blank' %>
    <div class=projectShortBlurb-<%=project.id%>></div>
    <div class=projectLikes-<%=project.id%>></div>
    <div class=projectLocation-<%=project.id%>></div>
    <%= link_to "View Project", project_path(project), :class => "more-#{project.id} view" %><br><br>
    </div></center>
    <br><br>
  <% else %>
    <%= link_to project.title, project_path(project), :class => "project_title" %><br><br>
    <center><%= link_to image_tag(project.image.url, class: 'media-object'), project.image.url, target: '_blank' %></center><br>
    <p class="created">Created by: <%= User.find(project.user_id).name %></p>
    <div class=projectShortBlurb-<%=project.id%>></div>
    <div class=projectLikes-<%=project.id%>></div>
    <div class=projectLocation-<%=project.id%>></div>
    <%= link_to "View Project", project_path(project), :class => "more-#{project.id} view" %><br><br>
    <br><br>
  <% end %>
<%end%>
</div>

<script type="text/javascript" charset="utf-8">

  $(function () {

  $(".view").hide();
  
  $(".project_title").on("click", function(event) {
    event.preventDefault();

    var projectUrl = event["target"]["pathname"];
    var project_str = projectUrl.substring(projectUrl.indexOf("p") + 1);
    var projectId = parseInt(project_str.match(/\d+/g).join(''));
    
    $.get(projectUrl + ".json", function(data) {
      
      var project = new Project(data.short_blurb, data.likes, data.location);
      project.display_project(); 

    });

    function Project(short_blurb, likes, location){
      this.short_blurb = short_blurb;
      this.likes = likes;
      this.location = location;

      this.display_project = function(){
        if($(".projectShortBlurb-" + projectId).text() == ""){
          $(".projectShortBlurb-" + projectId).text(short_blurb);
          $(".projectLikes-" + projectId).text("Likes: " + likes);
          $(".projectLocation-" + projectId).text(location);
          $(".more-"+projectId).show();
        }
        else{
          $(".projectShortBlurb-" + projectId).text("");
          $(".projectLikes-" + projectId).text("");
          $(".projectLocation-" + projectId).text("");
          $(".more-"+projectId).hide();
        }
       }
     }

  });
});
</script>

</script>

app/views/projects/new.html.erb
<p class="create_new">Create a new project</p>

<% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
<% end %>

<%= render "form" %>

app/views/projects/show.html.erb
<%= flash[:success] if flash[:success] %>
<br><br>

<% if current_user && current_user.created_projects.include?(@project) %>
  <%= link_to "Edit project", edit_project_path(@project), class: 'form_button' %>
    <%= link_to 'Delete project',  user_project_path(current_user, @project),
        data: { confirm: 'Are you sure you want to delete this project?' }, method: :delete, class: 'form_button' %>
<%end%>

<h1 class="project_title_1"><%= @project.title %></h1><br><br>

<center><div class="project">

  <br>
  <p class="creator">Created by: <%= @user_name %></p>

  <% if !@project.image_file_name.nil? %>
    <center><%= link_to image_tag(@project.image.url, class: 'media-object'), @project.image.url, target: '_blank' %></center>
  <%end%>
  <br>
  <p class="created"><%= @project.short_blurb %></p>
  <p><%= @project.location %></p>

  <div class="likes"><%= pluralize(@project.likes, 'like') %></div>

  <br><br><br>
  <% @project.categories.each do |category| %>
    <p><%= category.name %></p>
  <%end%>

</div></center>
<br>

<% if current_user && !current_user.created_projects.include?(@project) %>
  <%= link_to "Like", project_like_path(@project), class: 'btn btn-default glyphicon glyphicon-thumbs-up' %><br><br>
<%end%>

<% if !current_user %>
  <%= link_to "Sign in", user_session_path %> to like or post a comment!
<%end%>

<div id="form"> 
  <%= form_for ([@project, Comment.new(project_id: @project.id)]) do |f| %>
    <%= f.hidden_field :project_id %>
    <%= f.label "Comment" %><br>
    <%= f.text_area :content, class: 'text-area' %><br><br>
    <%= f.submit %>
  <%end%>
</div>
<br>
<a href="" class="comments">Load Comments:</a><br><br>

<center><div id="box">

  <div class='comment_div'></div>

  <% @project.comments.each_with_index do |comment, index| %>
    <div class=comment_content-<%=comment.id%>></div>
    <div class=comment_user-<%=comment.id%>></div>
    <br>
  <%end%>
</div></center>


<script type="text/javascript" charset="utf-8">

$(function () {

  $("form").hide();

  if(currentUser.id != ""){
    $("form").show();
  }

  $(".comments").click(function(event){

    event.preventDefault();

    var projectUrl = event["target"]["href"];
    var projectId = projectUrl.slice(-1);

    $.get(projectUrl + ".json", function(data) {

      if(data["comments"].length === 0){
        alert("There are no comments to display.");
      }

      else{

        data["comments"].forEach(function(object){

          if($("#box").text().indexOf(object.content) === -1){
            loadData(object);
          }
          else{
            event.preventDefault();
          }
        });
      }

    });

  });

  $('form').on('submit', function(event){
      event.preventDefault();
      var values = $(this).serialize();
      var projectUrl = event["target"]["baseURI"];
      var projectId = projectUrl.slice(-1);

      var posting = $.post('/projects/' + projectId + '/comments', values);

      posting.done(function(data) {
          postData(data);
      });

  });

  function loadData(data){
    var editLink = "../comments/" + data.id + "/edit";
    var deleteLink = "../comments/" + data.id;
     $(".comment_content-"+data.id).append(data.content + '</br>');
     $(".comment_user-"+data.id).append('By: ' + data["user"]["name"] + '</br></br>');

     if(window.currentUser.id == data["user"]["id"]){
      $(".comment_content-"+data.id).prepend("<div> <a href="+editLink+">Edit</a> <a data-method='delete' href="+deleteLink+">Delete</a></div>");
     }
  }


  function postData(data){

   var data_id = parseInt(data.id)
   var editLink = "../comments/" + data.id + "/edit";
   var deleteLink = "../comments/" + data.id + "/delete";

    $(".comment_div").append("<a href="+editLink+">Edit</a> ");
    $(".comment_div").append("<a href="+deleteLink+">Delete</a> </br>");
    $(".comment_div").append(data.content + '</br>');
    $(".comment_div").append("By: " + data.user.name + '</br></br>');
   
  }

})


</script>