config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  root 'welcome#index'
  
  resources :comments

  resources :categories, only: [:index, :show]

  resources :users, only: [:show, :index] do
    resources :projects, except: [:new]
  end

  resources :projects do
    resources :comments
    get 'like'
  end

  get 'current_user' => "users#current_user"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :project_categories
  has_many :projects, through: :project_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @category}
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1><br>

<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category.id), :class => "category" if category.name != "" %><br>
  <div class=box-<%=category.id%>>
   <% if category.name != "" %>
    <div class=projects-<%=category.id%> "category"></div><br>
   <%end%>
  </div>
<%end%>

<script type="text/javascript" charset="utf-8">
 
 $(function () {

  $(".category").click(function(event){

    event.preventDefault();

    var projectUrl = event["target"]["href"];
    var projectId = projectUrl.slice(-1);

    $.get(projectUrl + ".json", function(data) {

      if(data["projects"].length === 0){
        alert("There are no projects to display.");
      }

      else{

        data["projects"].forEach(function(object){
          var projectLink = "../projects/" + object.id;
          if($(".box-"+projectId).text().indexOf(object.title) === -1){
            $(".projects-"+projectId).append("<div><a href="+projectLink+">"+object.title+"</a></div>"); 
          }
          else{
            $(".projects-" + projectId).text("");
          }
        });

      }

    });

  });

})

</script>

app/views/categories/show.html.erb
<h1>Projects in <%=@category.name %></h1>

<% @category.projects.each do |project| %>
  <p><%= link_to project.title, project_path(project) %></p>
<%end%>