config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  root 'welcome#index'
  
  resources :comments

  resources :categories, only: [:index, :show]

  resources :users, only: [:show, :index] do
    resources :projects, except: [:new]
  end

  resources :projects do
    resources :comments
    get 'like'
  end

  get 'current_user' => "users#current_user"

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
        <% object.errors.full_messages.each do |msg| %>
          <%= msg %>.<br>
        <% end %>
   </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="header">
<div id="title">
<%= link_to "Creatify", root_path, :class => "title" %><br><br>
</div>

<br><br>
<nav class="nav">
    <ul>
          <% if current_user %>
            <%= link_to "Sign out", destroy_user_session_path, :class => "nav_button", method: :delete %>
          <%else%>
            <%= link_to "Sign In", user_session_path, :class => "nav_button"%>
            <%= link_to "Sign up", new_user_registration_path, :class => "nav_button" %>
          <% end %> 

          <%if current_user%>
            <%= link_to "New project", new_project_path, :class => "nav_button" %>
            <%= link_to "My projects", user_projects_path(current_user.id), :class => "nav_button" %>
          <%end%>

          <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class => "nav_button" %>

          <%= link_to "Discover", projects_path, :class => "nav_button" %>
          <%= link_to "Categories", categories_path, :class => "nav_button" %>
    </ul>
</nav>
</div>
<br><br><br>
<% if current_user %>
   <div class="welcome">Hello <%= current_user.name %>!<br><br></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Creatify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= content_tag(:div, flash[:error], id: "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], id: "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], id: "flash_alert") if flash[:alert] %>
<%= yield %>

</body>

<script type="text/javascript">
    window.currentUser = {
        id : "<%=current_user.id if current_user %>",
    }
</script>

</html>